### PR TITLE
Fixing impala agent independent tensor shape bug

### PR DESCRIPTION
**Pull request by AizazSharif**
Hi @praveen-palanisamy,

Kindly look into the pull request regarding the bug we discussed in #11. The code is working now.

Regards,
Aizaz Sharif

### CODE REVIEW

**Comment by praveen-palanisamy** [comment]
Hey @AizazSharif !
Thanks for the PR. You are right, the config wasn't being passed to RLLib properly.
I had refactored the script and pushed to this branch: https://github.com/praveen-palanisamy/macad-agents/tree/fix-impala-ma-inde-research-script
But didn't create/merge as a PR. 

I briefly reviewed your PR and it looks like there are some default argument changes as well and the configs are repeated in two places. If you could please update that, we can use this PR.

**Comment by AizazSharif** [comment]
Hi @praveen-palanisamy ,

I have added back default argument values within the branch changes you made above. Kindly check.

**Review by praveen-palanisamy — CHANGES_REQUESTED** [review]
Hey @AizazSharif !
Thanks for the PR. You are right, the config wasn't being passed to RLLib properly.
I had refactored the script and pushed to this branch: https://github.com/praveen-palanisamy/macad-agents/tree/fix-impala-ma-inde-research-script
But didn't create/merge as a PR.

I briefly reviewed your PR and it looks like there are some default argument changes as well and the configs are repeated in two places. If you could please update that, we can use this PR.

**Comment by praveen-palanisamy** [comment]
Thanks for the update. Looks like the review comments I had left yesterday got updated only after I refreshed the page today by then you had already pushed the update! Ignore them for now. I'll review your latest change and update.

**Review by praveen-palanisamy — APPROVED** [review]
LGTM

**Pull request merged**
